### ISSUE TITLE
Does this supports multilingual versions? (mT5)

### ISSUE THREAD

**Issue by cramraj8** [terrierteam/pyterrier_t5#11]
I wonder if the same monolingual codebase can be adapted for unicamp-dl/mt5-13b-mmarco-100k or unicamp-dl/mt5-base-en-msmarco.

**Comment by seanmacavaney** [comment]
@andreaschari you had integrations for other languages at some point, right?

IIRC, one of the key challenges is that the prompt and/or target tokens are not stored as part of the model's configuration, so anything that uses them needs to have its own mapping of model ID -> prompt/target tokens, which is a bit brittle.

**Comment by andreaschari** [comment]
There's this attempt I made a few years ago. I hope there's something useful there @cramraj8 : https://github.com/andreaschari/pyterrier_t5/blob/master/pyterrier_t5/__init__.py

**Comment by cramraj8** [comment]
Thank you very much @seanmacavaney and @andreaschari !! The pointed mt5 module works well. It actually solved the error (`mT5Config doesn't have n_positions so we fallback to 512`) I was getting too.

**Comment by cmacdonald** [comment]
Can we make a PR that merges this into the main repo?
