### ISSUE TITLE
Dealing long documents into passages

### ISSUE THREAD

**Issue by somnath-banerjee** [terrierteam/pyterrier_t5#3]
Thanks for the examples.
Please give a mono/duoT5 example that shows how to deal with long documents into smaller passages. Because in the usual case, the documents are longer than 512 tokens. 
Given: dataframe: ['docno','text'] and Indexer: DFIndexer

**Comment by cmacdonald** [comment]
See the PyTerrier documentation here:
https://pyterrier.readthedocs.io/en/latest/text.html#working-with-passages-rather-than-documents

**Comment by somnath-banerjee** [comment]
Thanks a lot. It worked for me.
--------------------------------------------------------------
monot5 = MonoT5ReRanker(text_field='body')
t5_pipe = ( pt.BatchRetrieve(index, wmodel="BM25", metadata=["docno", "body"])
    >> pt.text.sliding(text_attr="body",length=512, stride=50, prepend_title=False)
    >> monot5  #pt.text.scorer(wmodel="BM25")
    >> pt.text.max_passage() 
    )
R = t5_pipe.search("query text")

**Comment by cmacdonald** [comment]
Super :-)
