### ISSUE TITLE
Open source license

### ISSUE THREAD

**Issue by janheinrichmerker** [terrierteam/pyterrier_t5#7]
To allow for re-using the code in other research, please consider adding an OSI-approved license to the code.
You can quickly choose a license template [here](https://github.com/terrierteam/pyterrier_t5/community/license/new?branch=master&filename=LICENSE). My all-time favorite would be the MIT license, but of course the choice is yours.

**Comment by seanmacavaney** [comment]
How about MPL 2.0? That's what PyTerrier itself uses.

**Comment by janheinrichmerker** [comment]
Sure :+1:
The difference would mostly be that with MPL-2.0 any derived source code must be licensed under the same terms.
MIT is more open, but also requires no attribution, which might not be what you want.

**Comment by janheinrichmerker** [comment]
Nice, thanks :+1:
